### ISSUE TITLE
Support of tap mode?

### ISSUE THREAD

**Issue by lmq1999** [slingamn/namespaced-openvpn#43]
I encounter a problem when trying to run namespace-OpenVPN in **dev tap**

When I run **dev tun**, It works just fine. Can you add support for tap mode ?

```                                                                            
Traceback (most recent call last):                                                                                                                    
  File "/root/namespaced-openvpn/namespaced-openvpn", line 399, in <module>                                                                           
    sys.exit(main())                                                                                                                                  
  File "/root/namespaced-openvpn/namespaced-openvpn", line 370, in main                                                                               
    return route_up(sys.argv[1:])                                                                                                                     
  File "/root/namespaced-openvpn/namespaced-openvpn", line 186, in route_up                                  
    have_ipv4 = assert_all_or_none(                                                                                                                   
  File "/root/namespaced-openvpn/namespaced-openvpn", line 163, in assert_all_or_none              
    raise ValueError(message, *variables)                                                                                                             
ValueError: ('Bad ipv4 options pushed from server', '10.0.1.1', None)  
```

**Comment by slingamn** [comment]
Thanks for the report. I'd have to look deeper into what kind of environment variables openvpn publishes for a tap adapter. However, a lot of the existing code is specific to layer 3 (e.g., adding the IP address and the routes), so I suspect that for tap, it may be easier to write a separate script altogether.
